config/routes.rb
Rails.application.routes.draw do
  get 'cards/new'
  get 'users/show'
  get 'items/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :users, only: [:show, :update]
  resources :cards, only: [:new, :create]
  resources :items, only: :order do
    post 'order', on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  attr_accessor :card_token
  validates :card_token, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_one :item_order
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :card, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end

  def create
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    customer = Payjp::Customer.create(
      description: 'test', # テストカードであることを説明
      card: params[:card_token] # 登録しようとしているカード情報
    )
    card = Card.new( # 顧客トークンとログインしているユーザーを紐付けるインスタンスを生成
      card_token: params[:card_token],  #カード情報
      customer_token: customer.id, # 顧客トークン
      user_id: current_user.id # ログインしているユーザー
    )
    if card.save
      redirect_to root_path
    else
      redirect_to action: "new" # カード登録画面へリダイレクト
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: :order  # 「find_item」を動かすアクションを限定

  def index
    @items = Item.all
  end

  def order # 購入する時のアクションを定義
    redirect_to new_card_path and return unless current_user.card.present?

    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    customer_token = current_user.card.customer_token # ログインしているユーザーの顧客トークンを定義
    Payjp::Charge.create(
      amount: @item.price, # 商品の値段
      customer: customer_token, # 顧客のトークン
      currency: 'jpy' # 通貨の種類（日本円）
    )

    ItemOrder.create(item_id: params[:id]) # 商品のid情報を「item_id」として保存する

    redirect_to root_path
  end

  private

  def find_item
    @item = Item.find(params[:id]) # 購入する商品を特定
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"] # 環境変数を読み込む
    card = Card.find_by(user_id: current_user.id) # ユーザーのid情報を元に、カード情報を取得

    redirect_to new_card_path and return unless card.present?

    customer = Payjp::Customer.retrieve(card.customer_token) # 先程のカード情報を元に、顧客情報を取得
    @card = customer.cards.first
  end

  def update
    if current_user.update(user_params) # 更新出来たかを条件分岐する
      redirect_to root_path # 更新できたらrootパスへ
    else
      redirect_to action: "show" # 失敗すれば再度マイページへ
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email) # 編集出来る情報を制限
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/new.html.erb
<%= form_with  url: cards_path, id: 'charge-form', class: 'card-form',local: true do |f| %>
  <div class="Cardpage">
    <h1>カード登録</h1>
  </div><br>
  <div class='form-wrap'>
    <%= f.label :number, "【カード番号】" %>
    <%= f.text_field :number, class:"number", placeholder:"カード番号(半角英数字)", maxlength:"16" %>
  </div>
  <div class='form-wrap'>
    <%= f.label :cvc ,"【ＣＶＣ】" %>
    <%= f.text_field :cvc, class:"cvc", placeholder:"カード背面にある3桁の番号", maxlength:"4" %>
  </div>
  <div class='form-wrap'>
  <br>
    <p>【有効期限】</p>
    <div class='input-expiration-date-wrap'>
      <%= f.select :exp_month, 1..12, {include_blank: "---"}, class: "exp_month" %>
      <p>月</p>
      <%= f.select :exp_year, 20..25, {include_blank: "---"}, class: "exp_year" %>
      <p>年</p>
    </div>
  </div>
  <%= f.submit "登録する" , class:"button" , id:"button" %>
<% end %>

app/views/items/index.html.erb
<%= link_to 'マイページへ行く', user_path(current_user) %>
<div class="content">
  <% @items.each do |item| %> 
<%# eachメソッドを使うことで、全商品に対して以下の処理を実行します %>
    <p>商品名：<%= item.name %></p>
    <p>値段：<%= item.price %>円</p>
    <%# もしitem_orderテーブルに保存されていたら %>
    <% if item.item_order != nil %> 
      <div class='sold-out'>
        <b>Sold Out!!</b>
      </div>
    <% else %> 
      <%= link_to '購入する', order_item_path(item.id), method: :post %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PayjpApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.pay.jp/" , type="text/javascript"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="AccountPage">
  <div class="AccountPage__title">
    <h1>マイページ</h1>
  </div><br>
    <div class="Card__title">
    <h2>カード情報</h2>
  </div>
  <div class="Card_info">
    【カード番号】
    <br>
    <%= "**** **** **** " + @card[:last4] %>
    <%# カード番号の下4桁を取得 %>

    <br>
    【有効期限】
    <br>
    <%= @card[:exp_month] %>
    <%# 有効期限の「月」を取得 %>
    /
    <%= @card[:exp_year] %>
    <%# 有効期限の「年」を取得 %>
  </div>
  <div class="Account__info">
    <h2>ユーザー情報</h2>
  </div>
  <div class="AccountPage__form">
    <%= form_for(current_user) do |f| %>
      <div class="FormField">
        <div class="FormField__name">
          <%= f.label :name %>
        </div>
        <div class="FormField__name">
          <%= f.text_field :name, autofocus: true %>
        </div>
      </div>
      <div class="FormField">
        <div class="FormField__email">
          <%= f.label :email %>
        </div>
        <div class="FormField__email">
          <%= f.email_field :email %>
        </div>
        <br>
      </div>
      <%= f.submit "更新する" %>
    <% end %>
    <br>
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete%>
    <br>
    <%= link_to "商品一覧へ戻る", root_path%>
  </div>
</div>